language: go
go:
  - 1.8

branches:
  only:
    - master
    - develop

before_install:
  - echo "before_install"

install:
  - echo "install"

before_script:
  - echo "install"
  - echo -n "" > coverage.txt

script:
  - go test -race -coverprofile=main.out -covermode=atomic
  - go test ./add -race -coverprofile=add.out -covermode=atomic

after_success:
  - cat main.out >> coverage.txt
  - cat add.out >> coverage.txt
  - bash <(curl -s https://codecov.io/bash)