language: go
go:
  - 1.8

branches:
  only:
    - master
    - develop

before_install:
  - echo "before_install"

install:
  - echo "install"

before_script:
  - echo "install"

script:
  - go test
  - go test ./add

after_success:
  - echo "success"
